#!/bin/bash

echo "DISABLE STEAM CLOUD FOR BEST EXPERIENCE"

### Variables
DESKTOPFILE=~/.local/share/applications/DELTARUNE.desktop
PREFIX_LOCATION=~/.local/share/Steam/steamapps/compatdata/1671210/pfx
SAVE_LOCATION=~/.local/share/DELTARUNESAVESWITCHER
APPDATAFOLDER=$PREFIX_LOCATION/drive_c/users/steamuser/AppData/Local
###

mkdir -p $SAVE_LOCATION
if [ ! -d "$SAVE_LOCATION/DEFAULT" ]; then
  echo No Default Save File
  mkdir $SAVE_LOCATION/DEFAULT
  cp $APPDATAFOLDER/DELTARUNE/* $SAVE_LOCATION/DEFAULT
  rm -ir $APPDATAFOLDER/DELTARUNE/
fi
echo "AVALIABLE SAVES (TO MAKE NEW ONES JUST TYPE A UNLISTED NAME)"
ls $SAVE_LOCATION
echo "SAVENAME:"
read SAVENAME

rm $APPDATAFOLDER/DELTARUNE
mkdir -p $SAVE_LOCATION/$SAVENAME
touch $SAVE_LOCATION/$SAVENAME/NOTEMPTY
ln -s $SAVE_LOCATION/$SAVENAME $APPDATAFOLDER/DELTARUNE

dex $DESKTOPFILE
