#!/bin/bash

echo "DISABLE STEAM CLOUD FOR BEST EXPERIENCE"

### Variables
DESKTOPFILE=${DESKTOPFILE:=~/.local/share/applications/DELTARUNE.desktop}
PREFIX_LOCATION=${PREFIX_LOCATION:=~/.local/share/Steam/steamapps/compatdata/1671210/pfx}
SAVE_LOCATION=${SAVE_LOCATION:=~/.local/share/DELTARUNESAVESWITCHER}
APPDATAFOLDER=${APPDATAFOLDER:=$PREFIX_LOCATION/drive_c/users/steamuser/AppData/Local}
###

echo "DESKTOP FILE: $DESKTOPFILE"
echo "PREFIX LOCATION: $PREFIX_LOCATION"
echo "SAVE LOCATION: $SAVE_LOCATION"
echo "APPDATA FOLDER: $APPDATAFOLDER"

mkdir -p $SAVE_LOCATION
if [ ! -d "$SAVE_LOCATION/DEFAULT" ]; then
  echo No Default Save File
  mkdir $SAVE_LOCATION/DEFAULT
  cp $APPDATAFOLDER/DELTARUNE/* $SAVE_LOCATION/DEFAULT
  rm -ir $APPDATAFOLDER/DELTARUNE/
fi
echo "AVALIABLE SAVES (TO MAKE NEW ONES JUST TYPE A UNLISTED NAME)"
ls $SAVE_LOCATION
echo "SAVENAME:"
read SAVENAME

rm $APPDATAFOLDER/DELTARUNE
mkdir -p $SAVE_LOCATION/$SAVENAME
touch $SAVE_LOCATION/$SAVENAME/NOTEMPTY
ln -s $SAVE_LOCATION/$SAVENAME $APPDATAFOLDER/DELTARUNE

dex $DESKTOPFILE
