#!/bin/bash

echo DISABLE STEAM CLOUD

### Variables
DESKTOPFILE=~/.local/share/applications/Undertale.desktop
SAVE_LOCATION=~/.local/share/UNDERTALESAVESWITCHER
APPDATAFOLDER=~/.config/UNDERTALE
###

mkdir -p $SAVE_LOCATION
if [ ! -d "$SAVE_LOCATION/DEFAULT" ]; then
  echo No Default Save File
  mkdir $SAVE_LOCATION/DEFAULT
  cp $APPDATAFOLDER/* $SAVE_LOCATION/DEFAULT
  rm -ir $APPDATAFOLDER/
fi
echo "AVALIABLE SAVES (TO MAKE NEW ONES JUST TYPE A UNLISTED NAME)"
ls $SAVE_LOCATION
echo "SAVENAME:"
read SAVENAME

rm $APPDATAFOLDER
mkdir -p $SAVE_LOCATION/$SAVENAME
ln -s $SAVE_LOCATION/$SAVENAME $APPDATAFOLDER

dex $DESKTOPFILE
